import streamlit as st
import tensorflow as tf
import numpy as np
import json
import os
import pandas as pd
from PIL import Image
from geopy.geocoders import Nominatim

# -------------------------------
# Environment Variables
# -------------------------------
from dotenv import load_dotenv

load_dotenv()
mistral_api_key = os.getenv("MISTRAL_API_KEY")

# -------------------------------
# LangChain & Mistral Imports
# -------------------------------
from langchain_mistralai import ChatMistralAI
from langchain_core.prompts import PromptTemplate

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(
    page_title="Plant Disease Detection",
    page_icon="🌿",
    layout="centered"
)

# -------------------------------
# Load Model & Labels
# -------------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("plant_disease_mobilenetv2.keras")

@st.cache_resource
def load_labels():
    with open("class_indices.json") as f:
        class_indices = json.load(f)
    return {v: k for k, v in class_indices.items()}

model = load_model()
labels = load_labels()

# -------------------------------
# Sidebar
# -------------------------------
with st.sidebar:
    st.header("ℹ️ About")
    st.write("""
    **Plant Disease Detection App**
    A deep learning web application that classifies **38 plant leaf diseases** and provides AI-driven remedies.
    """)
    st.markdown("---")
    st.markdown("👨‍💻 **Developer:** Nihal Ahemad Khan")
    st.markdown("📧 **Email:** nihalahemad2003@gmail.com")
    st.markdown("🔗 **LinkedIn:** [Profile](https://linkedin.com/in/nihal-ahemad-khan)")

# -------------------------------
# Main Title
# -------------------------------
st.title("🌿 Plant Disease Detection & AI Remedies")
st.write("Upload a leaf image to get predictions, expert advice, and find local help centers.")

# -------------------------------
# Image Upload & Prediction
# -------------------------------
uploaded_file = st.file_uploader("Upload Leaf Image", type=["jpg", "jpeg", "png"])

if uploaded_file:
    # 1. Display Image & Predict
    image = Image.open(uploaded_file).convert("RGB")
    
    col1, col2 = st.columns([1, 1])
    with col1:
        st.image(image, caption="Uploaded Image", width="stretch")
    
    img = image.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)
    class_id = np.argmax(preds)
    confidence = preds[0][class_id] * 100
    predicted_disease = labels[class_id]

    with col2:
        st.markdown("<br>", unsafe_allow_html=True)
        st.success(f"🦠 **Predicted Disease:**\n### {predicted_disease}")
        st.write(f"**Confidence:** {confidence:.2f}%")
        st.progress(float(confidence / 100))

    # -------------------------------
    # AI Advice Generation
    # -------------------------------
    if mistral_api_key:
        st.markdown("---")
        st.subheader("🌾 AI Agricultural Assistant")
        
        with st.spinner("Generating expert advice for Indian farmers..."):
            try:
                llm = ChatMistralAI(
                    mistral_api_key=mistral_api_key, 
                    model="mistral-large-latest", 
                    temperature=0.3
                )
                
                template = """
                You are an expert agricultural consultant in India. 
                A farmer's plant has the disease: {disease}.
                Provide a structured response:
                1. 🧪 Remedies & Immediate Actions
                2. 📞 Helplines (e.g., Kisan Call Center)
                3. 🏛️ Government Assistance & Schemes
                """
                
                prompt = PromptTemplate(input_variables=["disease"], template=template)
                chain = prompt | llm
                response = chain.invoke({"disease": predicted_disease})
                
                # Display Result
                st.markdown(response.content)

                # -------------------------------
                # FEATURE 1: Downloadable Report
                # -------------------------------
                report_content = f"""
                🌿 PLANT DISEASE DIAGNOSIS REPORT 🌿
                -----------------------------------
                Predicted Disease: {predicted_disease}
                Model Confidence:  {confidence:.2f}%
                
                --- EXPERT ADVICE ---
                {response.content}
                
                Generated by Plant Disease Detection App 
                Developer: Nihal Ahemad Khan
                """
                
                st.download_button(
                    label="📄 Download Advice Report (.txt)",
                    data=report_content,
                    file_name=f"{predicted_disease.replace(' ', '_')}_report.txt",
                    mime="text/plain",
                    help="Click to download this advice to your device."
                )
                
            except Exception as e:
                st.error(f"AI Error: {e}")

# -------------------------------
# FEATURE 2: Google Maps Integrated Center Finder
# -------------------------------
st.markdown("---")
st.subheader("📍 Real Agricultural Help Centers")
st.write("Find a verified center and get instant directions via Google Maps.")

# 1. Database of Real Centers (Focusing on Maharashtra/India for your project)
# You can add more states/districts here to make it look even more complete
centers_data = {
    "Pusad": [
        {"name": "Krishi Vigyan Kendra (KVK), Sagroli", "address": "Pusad-Washim Road, Yavatmal, Maharashtra"},
        {"name": "Vasantrao Naik Marathwada Krishi Vidyapeeth", "address": "Pusad, Yavatmal, Maharashtra"}
    ],
    "Pune": [
        {"name": "College of Agriculture, Pune", "address": "Shivajinagar, Pune, Maharashtra"},
        {"name": "KVK Narayangaon", "address": "Narayangaon, Pune, Maharashtra"}
    ],
    "Delhi": [
        {"name": "ICAR - Indian Agricultural Research Institute", "address": "Pusa, New Delhi, Delhi"},
        {"name": "National Board of Plant Genetic Resources", "address": "Pusa Campus, New Delhi"}
    ]
}

# 2. UI for selection
selected_city = st.selectbox("Select your nearest major city:", list(centers_data.keys()))

if selected_city:
    st.write(f"Showing centers near **{selected_city}**:")
    
    # Display centers in a clean layout
    for center in centers_data[selected_city]:
        with st.expander(f"🏢 {center['name']}"):
            st.write(f"**Address:** {center['address']}")
            
            # Create a Google Maps Search URL
            # Format: https://www.google.com/maps/search/?api=1&query=Address+Name
            search_query = center['name'].replace(" ", "+") + "+" + center['address'].replace(" ", "+")
            google_maps_url = f"https://www.google.com/maps/search/?api=1&query={search_query}"
            
            # FANCY: Use the native Streamlit Link Button
            st.link_button("📍 View on Google Maps", google_maps_url)

# 3. Custom Search (If they want to find something else)
st.markdown("---")
st.write("**Can't find your city?** Search specifically on Google Maps:")
custom_search = st.text_input("Enter a specific center or village name:")
if custom_search:
    custom_url = f"https://www.google.com/maps/search/?api=1&query={custom_search.replace(' ', '+')}+Agricultural+Center"
    st.link_button(f"🔍 Search '{custom_search}' on Google Maps", custom_url)
# -------------------------------
# Footer
# -------------------------------
st.markdown("---")
st.markdown(
    "<center>🚀 Built with ❤️ by <b>Nihal Ahemad Khan</b></center>", 
    unsafe_allow_html=True
)